name: QA

on:
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Compute number of commits to fetch
      run: echo 'print "::set-env name=COMMITS::", ${{github.event.pull_request.commits}} + 1, "\n"' | bc
    - uses: actions/checkout@v2
      with:
       ref: ${{ github.event.pull_request.head.sha }}
       fetch-depth: ${{ env.COMMITS }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
    - name: Compute installed python version hash (for use in cache key)
      run: python -c 'import hashlib,sys;print("::set-env name=PY::",hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest(),sep="")'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: pre-commit run --from-ref ${{ github.event.pull_request.base.sha }} --to-ref HEAD --show-diff-on-failure --color=always
