name: QA

on:
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       ref: ${{ github.event.pull_request.head.sha }}
       fetch-depth: 0
    - name: Fetch base ref
      run: git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules origin ${{ github.base_ref }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
        echo ${{ github.event.pull_request.base.sha }}
    - name: set PY
      run: python -c 'import hashlib,sys;print("::set-env name=PY::",hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest(),sep="")'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: pre-commit run --from-ref $(git merge-base origin/${{ github.base_ref }} HEAD) --to-ref HEAD --show-diff-on-failure --color=always
