name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
       ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run pre-commit
      run: pre-commit run --from-ref ${{ github.base_ref }} --to-ref ${{ github.head_ref }} --show-diff-on-failure --color=always
